# Use the official Nginx base image
FROM nginx:latest

# Create a custom index.html file (optional)
COPY index.html /usr/share/nginx/html/index.html

# Copy Nginx configuration file
COPY nginx.conf /etc/nginx/nginx.conf

# Set the working directory to /var/opt/nginx
WORKDIR /var/opt/nginx